name: Build ExitLagBypassFinal

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout do código
      uses: actions/checkout@v3

    - name: Configurar Theos
      run: |
        brew install ldid xz
        git clone --recursive https://github.com/theos/theos.git $HOME/theos
        echo "THEOS=$HOME/theos" >> $GITHUB_ENV

    - name: Compilar tweak
      run: |
        make package FINALPACKAGE=1

    - name: Fazer upload do .deb compilado
      uses: actions/upload-artifact@v4
      with:
        name: ExitLagBypassFinal
        path: ./packages/*.deb
